<a href="https://colab.research.google.com/github/kamooshshaik/Banking-Risk-Analytics-Dashboard/blob/main/CE334_Deragula_Sujith_230351_Lab_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np # importing numpy(Numerical Python)

In [ ]:
#1. Create a row and column vector using the input method and manually.

# creating the row and column vectors manually and printing them:
row_mn=np.array([[1,2,3,4,5]])
clmn_mn=np.array([[1],[2],[3],[4],[5]])
print("Manually created vector: ")
print("Row vector: ",row_mn)
print("Column vector: ",clmn_mn)
print()

#  creating the row and column vectors using "Input Method" and printing them:
x=[int(x) for x in input("Enter 5 numbers for vector(space separated): ").split()]
row_im=np.array(x).reshape(1,-1) # reshaping x to row vector
clmn_im=np.array(x).reshape(-1,1) # reshaping x to column vector
print("vector created by Input method: ")
print("Row vector: ",row_im)
print("Column vector: ",clmn_im)

Manually created vector: 
Row vector:  [[1 2 3 4 5]]
Column vector:  [[1]
 [2]
 [3]
 [4]
 [5]]

Enter 5 numbers for vector(space separated): 3 5 2 5 99
vector created by Input method: 
Row vector:  [[ 3  5  2  5 99]]
Column vector:  [[ 3]
 [ 5]
 [ 2]
 [ 5]
 [99]]


In [ ]:
#2. Create a matrix (5 × 5) using the input method as well as manually, and save it as a.

# Manually:
a=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print("Manually created 5x5 matrix a:")
print(a)
print()

# Input method:
x=[int(x) for x in input("Enter 25 numbers of 5x5 matrix(space separated: )").split()]
a=np.array(x).reshape(5,5) # reshaping the list into 5×5 matrix
print("5x5 matrix a:")
print(a)

Manually created 5x5 matrix a:
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]

Enter 25 numbers of 5x5 matrix(space separated: )84 12 45 92 7 33 61 29 55 10 98 4 72 38 81 19 66 50 3 88 24 57 41 15 76
5x5 matrix a:
[[84 12 45 92  7]
 [33 61 29 55 10]
 [98  4 72 38 81]
 [19 66 50  3 88]
 [24 57 41 15 76]]


In [ ]:
# 3. Get the 3rd row out of the matrix
print("3rd row:", a[2])

3rd row: [98  4 72 38 81]


In [ ]:
# 4. Get the 4th column out of the matrix.
print("4th column:", a.T[3]) # on transposing a matrix columns becomes rows. so, the 4th row of the transposed matrix is 4th column of original matrix

4th column: [92 55 38  3 15]


In [ ]:
# 5. Sort the matrix row-wise and column-wise.
temp=a.copy() # copying the matrix a to temp

# if we want to sort the matrix row-wise and column-wise once:
a=np.sort(a,axis=1)
a=np.sort(a,axis=0)
print("Partially sorted matrix:")
print(a)

#if we need the fully sorted matrix(row-wise and column-wise):
a=temp
a=a.reshape(-1) # converting the matrix to 1D array
a=np.sort(a) # sorting all the elements
a=a.reshape(5,5) # reshaping back to 5×5 matrix
print("Fully sorted matrix:")
print(a)

Partially sorted matrix:
[[ 3 12 33 55 61]
 [ 4 19 41 57 76]
 [ 7 24 45 66 88]
 [10 29 50 81 92]
 [15 38 72 84 98]]
Fully sorted matrix:
[[ 3  4  7 10 12]
 [15 19 24 29 33]
 [38 41 45 50 55]
 [57 61 66 72 76]
 [81 84 88 92 98]]


In [ ]:
# 6. Apply a for loop on the matrix a: if an element is greater than 2, multiply the element by 10, and call it b.
temp=[] # Create an empty list
for i in a.flat: # iterating every element in the 5x5 matrix using 'flat'
  if i>2:
    temp.append(i*10) # If the element is greater than 2 then multiplying it by 10 and adding to list
  else:
    temp.append(i)# or else simply adding that element to the list
b=np.array(temp).reshape(5,5)  # reshaping the list to 5×5 matrix
print("Matrix b:")
print(b)


Matrix b:
[[ 30  40  70 100 120]
 [150 190 240 290 330]
 [380 410 450 500 550]
 [570 610 660 720 760]
 [810 840 880 920 980]]


In [ ]:
# 7. Add matrices a and b.
add=a+b # element-wise addition
print(add)

[[  33   44   77  110  132]
 [ 165  209  264  319  363]
 [ 418  451  495  550  605]
 [ 627  671  726  792  836]
 [ 891  924  968 1012 1078]]


In [ ]:
# 8. Subtract matrix b from a.
sub=b-a # each element of b is substracted from corresponding element of a
print(sub)

[[ 27  36  63  90 108]
 [135 171 216 261 297]
 [342 369 405 450 495]
 [513 549 594 648 684]
 [729 756 792 828 882]]


In [ ]:
# 9. Multiply matrix a by b element-wise and using matrix multiplication.
#element-wise:
product1=a*b # multiplying element-wise
print("Matrix multiplication a by b element-wise:")
print(product1)
print()
#using matrix multiplication:
print("Matrix multiplication product matrix:")
product2=np.matmul(a, b) # matrix multiplication
print(product2)

Matrix multiplication a by b element-wise:
[[   90   160   490  1000  1440]
 [ 2250  3610  5760  8410 10890]
 [14440 16810 20250 25000 30250]
 [32490 37210 43560 51840 57760]
 [65610 70560 77440 84640 96040]]

Matrix multiplication product matrix:
[[ 18770  19930  21480  23200  24890]
 [ 55680  59460  64590  70250  75650]
 [ 97440 104460 114150 124790 134740]
 [138540 148690 162730 178150 192470]
 [180290 193720 212390 232860 251800]]


In [ ]:
# 10. Divide each element of matrices a and b by 18.

# Dividing each element of matrices a and b by 18.
a=a/18
print("Matrix a after division:")
print(a)
print()
b=b/18
print("Matrix b after division:")
print(b)


Matrix a after division:
[[0.16666667 0.22222222 0.38888889 0.55555556 0.66666667]
 [0.83333333 1.05555556 1.33333333 1.61111111 1.83333333]
 [2.11111111 2.27777778 2.5        2.77777778 3.05555556]
 [3.16666667 3.38888889 3.66666667 4.         4.22222222]
 [4.5        4.66666667 4.88888889 5.11111111 5.44444444]]

Matrix b after division:
[[ 1.66666667  2.22222222  3.88888889  5.55555556  6.66666667]
 [ 8.33333333 10.55555556 13.33333333 16.11111111 18.33333333]
 [21.11111111 22.77777778 25.         27.77777778 30.55555556]
 [31.66666667 33.88888889 36.66666667 40.         42.22222222]
 [45.         46.66666667 48.88888889 51.11111111 54.44444444]]


In [ ]:
# 11. Find the inverse, rank, condition number, singular value decomposition, and the norm of matrices a and b.

# Inverse of a and b:
if np.linalg.det(a)!=0: # checking for det(a)!=0 cause Inverse wont exist if determinant=0(singular matrix)
    inv_a=np.linalg.inv(a)
    print("Inverse of matrix a:\n",inv_a)
else:
    print("Matrix a is singular, inverse does not exist")
if np.linalg.det(b)!=0: # checking for det(b)!=0 cause Inverse wont exist if det(b)=0
    inv_b=np.linalg.inv(b)
    print("Inverse of matrix b:\n",inv_b)
else:
    print("Matrix b is singular, inverse does not exist")
print()

# rank of a and b:
rank_a=np.linalg.matrix_rank(a)
rank_b=np.linalg.matrix_rank(b)
print("Rank of matrix a:",rank_a)
print("Rank of matrix b:",rank_b)
print()

# condition number of a and b:
cond_a=np.linalg.cond(a)
cond_b=np.linalg.cond(b)
print("Condition number of matrix a:",cond_a)
print("Condition number of matrix b:",cond_b)
print()

# Singular Value Decomposition(SVD) of a and b:
# Decomposing matrix a into U, Singular Values (S), and V-transpose (V^T)
U_a,S_a,VT_a=np.linalg.svd(a)
print("SVD of matrix a:")
print("U:\n",U_a)
print("Singular values:\n",S_a)
print("V^T:\n",VT_a)
# Decomposing matrix b into U, Singular Values (S), and V-transpose (V^T)
U_b,S_b,VT_b=np.linalg.svd(b)
print("SVD of matrix b:")
print("U:\n",U_b)
print("Singular values:\n",S_b)
print("V^T:\n",VT_b)
print()

# norm of a and b:
norm_a=np.linalg.norm(a)
norm_b=np.linalg.norm(b)
print("Norm of matrix a:", norm_a)
print("Norm of matrix b:", norm_b)



Inverse of matrix a:
 [[ 12.57473163  -8.6209744    0.50536746  -0.50536746   1.47151115]
 [-24.19818332   2.97274979  15.96366639   2.03633361  -8.57638315]
 [ 12.2625929   14.06110652 -29.25185797  -6.74814203  15.41370768]
 [  0.63914121  -9.58711808   5.21717589  12.78282411  -9.69116433]
 [ -1.26341866   0.95127993   7.26837325  -7.26837325   1.57555739]]
Inverse of matrix b:
 [[ 1.25747316 -0.86209744  0.05053675 -0.05053675  0.14715111]
 [-2.41981833  0.29727498  1.59636664  0.20363336 -0.85763832]
 [ 1.22625929  1.40611065 -2.9251858  -0.6748142   1.54137077]
 [ 0.06391412 -0.95871181  0.52171759  1.27828241 -0.96911643]
 [-0.12634187  0.09512799  0.72683732 -0.72683732  0.15755574]]

Rank of matrix a: 5
Rank of matrix b: 5

Condition number of matrix a: 730.6229409401877
Condition number of matrix b: 730.6229409401781

SVD of matrix a:
U:
 [[-0.06094768 -0.46024121 -0.26701203 -0.67485892 -0.50767453]
 [-0.19933325 -0.70828274  0.10244215  0.6302379  -0.22562715]
 [-0.37546387

In [ ]:
# 12. Find the norm, inner product, and outer product of the column vector.

# norm of the column vector:
norm_v=np.linalg.norm(clmn_im)
print("Norm of the column vector:",norm_v)
print()

# inner product:
in_pro=np.dot(clmn_im.T,clmn_im)
print("Inner product of the column vector:",in_pro)
print()

# outer product of the column vector:
out_pro=np.dot(clmn_im,clmn_im.T)
print("Outer product of the column vector:",out_pro)



Norm of the column vector: 99.31767214348109

Inner product of the column vector: [[9864]]

Outer product of the column vector: [[   9   15    6   15  297]
 [  15   25   10   25  495]
 [   6   10    4   10  198]
 [  15   25   10   25  495]
 [ 297  495  198  495 9801]]


In [ ]:
# 13. Write a function called derivative which takes input parameters f(x), a, method (forward, backward, and central),
# and h (step size) (with default values method=‘central’ and h = 0.01). The function should return the corresponding
# difference formula for the derivative of the function at a with step size h. Test your function on e^x and
# cos x at x = 0.5.

def derivative(f,a,method='central',h=0.01):
    if method=='forward':
        return (f(a+h)-f(a))/h
    elif method=='backward':
        return (f(a)-f(a-h))/h
    elif method=='central':
        return (f(a+h)-f(a-h))/(2*h)
    else:
        raise ValueError("Invalid Method. It must be 'forward', 'backward', or 'central'")

# testing:
f1=np.exp
print("Derivative of e^x at x=0.5")
print("Forward :",derivative(f1,0.5,'forward'))
print("Backward:",derivative(f1,0.5,'backward'))
print("Central :",derivative(f1,0.5))
print("Exact value:",np.exp(0.5))
print()

f2 = np.cos
print("Derivative of cos(x) at x=0.5")
print("Forward :",derivative(f2,0.5,'forward'))
print("Backward:",derivative(f2,0.5,'backward'))
print("Central :",derivative(f2,0.5))
print("Exact value:",-np.sin(0.5))



Derivative of e^x at x=0.5
Forward : 1.6569924245758205
Backward: 1.6405050744749294
Central : 1.648748749525375
Exact value: 1.6487212707001282

Derivative of cos(x) at x=0.5
Forward : -0.483805424462147
Backward: -0.4750296719748692
Central : -0.4794175482185081
Exact value: -0.479425538604203


In [ ]:
# 14. Download the Automatic Weather Station AWS Data. Read the .csv file using the Pandas library as a DataFrame.
import pandas as pd # importing pandas
data=pd.read_csv("AWS(in).csv")  # reading CSV file into DataFrame
print(data) # displaying the data


                    created_at  entry_id  Soil Temperature  Soil Moisture  \
0    2022-12-14T14:19:11+05:30     10830             21.06            817   
1    2022-12-14T14:20:13+05:30     10831             21.06            817   
2    2022-12-14T14:21:15+05:30     10832             21.06            817   
3    2022-12-14T14:22:18+05:30     10833             21.06            817   
4    2022-12-14T14:23:20+05:30     10834             21.06            817   
..                         ...       ...               ...            ...   
654  2022-12-26T14:37:18+05:30     11484             20.50            818   
655  2022-12-26T15:17:18+05:30     11485           4095.94            818   
656  2022-12-26T15:57:59+05:30     11486             20.50            818   
657  2022-12-26T16:58:03+05:30     11487             20.00            816   
658  2022-12-26T17:18:03+05:30     11488             19.75            816   

     Wind Speed  Rainfall  Temperature  Humidity  Pressure  Battery Voltage

Marks : /10